
version: '3'
services:
  frontend:
    image: qa-challenge-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    depends_on:
      - backend
  backend:
    image: qa-challenge-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000